// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "sidesideeffect.io",
            "url": "https://github.com/shlason/imgproxy",
            "email": "nocvi111@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/shlason/imgproxy/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/image": {
            "get": {
                "description": "抓取由指定參數所處理過後的圖片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "image"
                ],
                "summary": "抓取圖片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Image URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Desire Width",
                        "name": "width",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Desire height",
                        "name": "height",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "fit or fill",
                        "name": "resize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Desire blur",
                        "name": "blur",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "image/png",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.responseFormat"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.responseFormat"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.responseFormat": {
            "type": "object",
            "properties": {
                "message": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "imgproxy.sidesideeffect.io",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Image-Proxy Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
